config/routes.rb
MyFirstApp::Application.routes.draw do

  root :to => 'first#index'

  match 'cats' => 'first#cats', :via => :get, :as => 'cats'

  match 'about' => 'first#about_us', :via => :get, :as => 'about_us'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
	#This is an action called index.
	def index
  end
  # Rails will now automatically load up the view of the same name
  # from the app/views/first folder: index.html.erb.
  def cats
  end
  def about_us
    @title = 'About Us'
    @content = 'This company was built on blood sweat and tears.'
  end    #autotmatically load: app/views/first/about_us.html.erb
         #this view will have access to the @title and @content variables
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/views/first/about_us.html.haml
%h1= @title
%h1= @content

app/views/first/cats.html.haml
%h2 MEOW

app/views/first/index.html.haml
%h1 woot
%p This is the paragraph of our first rails view 
%h2 BRING IT WHATWHAT WAHHHHHHTTTTTUGH


app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Awesome Rails Title
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  %body
    %header
      %h1 My Awesome Rails App
      %ul
        %li= link_to 'Home', root_path
        %li= link_to 'About Us', about_us_path
        %li= link_to 'Cats', cats_path
    #main
      = yield
    %footer
      %p Copywrong 2013